# Site settings
title: VisionSpace
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to VisionSpace! (edit this in _config.yml) Let's see what we can do?
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: VisionSpace
github_username:  VisionSpace

# Build settings
markdown: kramdown
